[mssql]
server = 10.1.6.177,1433
database = UnitTrust
user = sa
password = Tongyu@123456
driver = SQL Server
encrypt = no
trust_server_certificate = yes

; [postgresql]
; host = localhost
; port = 15432
; database = wm
; user = wealth
; password = wealth123
; schema = auth_service


[postgresql]
host = 10.1.6.178
port = 15432
database = wm
user = wealth
password = wealth@123
